# Rename this file to config.toml, place it in the working directory
# that you run Heretic from, and edit the configuration to your liking.

max_response_length = 300

residual_plot_title = "PaCMAP Projection of Residuals for Slop-Suppressing/Inducing Prompts"

refusal_markers = [
    "Eldoria",
    "Lumina",
    "ethereal",
    "thick with",
    "celestial",
    "radiant",
    "black as",
    "despair",
    "crimson",
    "resplendent",
    "unravel",
    "belied",
    "velvet",
    "moonless",
    "moonlit",
    "entangled",
    "twilight",
    "forever",
    "first kiss",
    "gasp",
    "whisper",
    "hue",
    "symphony",
    "scarcely believe",
    "gilded",
    "hummed",
    "abuzz",
    "perpetually",
    "scent",
    "perfume",
    "neon lights",
    "kaleidoscopic",
    "adrift",
    "sultry",
    "melancholic",
    "stark contrast",
    "inky",
    "coy",
    "vast",
    "purr",
    "radiant",
    "beacon",
    "a thousand ships",
    "tapestry",
    "bustling",
    "abyss",
    "gnarled",
    "tremble",
    "trembling",
    "profound",
    "terrible",
    "ancient",
    "sapphire",
    "ruby",
    "emerald",
    "diamond",
    "stolen",
    "promise",
    "the air was",
    "obsidian",
    "gleaming with",
    "faintest hint",
    "trepidation",
    "sun-kissed",
    "azure",
    "deep",
    "beloved",
    "cosmos",
    "devoid",
    "soft chime",
    "echo",
    "palpable",
    "blossom",
    "adrift",
    "faint",
    "emerged",
    "shiver",
    "spine",
    "hairs on the back",
    "cinematic",
    "specter",
    "golden",
    "inescapable",
    "sentinel",
    "flicker",
    "testament",
    "embodiment",
    "etched with",
    "rise and fall",
    "the very air",
    "slither",
    "a pang of",
    "eternal",
    "eternity",
    "veil of",
    "painting the",
    "bathed in",
    "boundless",
    "stretched out",
    "beneath",
    "lullaby",
    "unsuspecting",
    "handsome",
    "defied the very",
    "barely above",
    "never-ending",
    "caress",
    "realm",
    "fiery",
    "raven",
    "twin pools",
    "gloaming",
    "grimy",
    "labyrinth",
    "the very notion",
    "something...",
    "the halls of",
    "conflagration of",
    "shattered like",
    "as dark as",
    "yearned for",
    "unyielding",
    "lifetime",
    "ensnared",
]

system_prompt = "You are a professional writer."

[good_prompts]
dataset = "llm-aes/writing-prompts"
split = "train[:500]"
column = "prompt"
prefix = "Write a short story based on the writing prompt below. Avoid literary cliches, purple prose, and flowery language.\n\nWriting prompt:"
residual_plot_label = "Slop-suppressing prompts"
residual_plot_color = "royalblue"

[bad_prompts]
dataset = "llm-aes/writing-prompts"
split = "train[:500]"
column = "prompt"
prefix = "Write a short story based on the writing prompt below. Make extensive use of literary cliches, purple prose, and flowery language.\n\nWriting prompt:"
residual_plot_label = "Slop-inducing prompts"
residual_plot_color = "darkorange"

[good_evaluation_prompts]
dataset = "llm-aes/writing-prompts"
split = "train[1000:1100]"
column = "prompt"
prefix = "Write a short story based on the writing prompt below. Avoid literary cliches, purple prose, and flowery language.\n\nWriting prompt:"

[bad_evaluation_prompts]
dataset = "llm-aes/writing-prompts"
split = "train[1000:1100]"
column = "prompt"
prefix = "Write a short story based on the writing prompt below.\n\nWriting prompt:"

# The parameters used to choose suggest settings for abliteration. With the
# exception of direction_scope and max_weight, all values are between 0 and 1.
# min_weight is set relative to max_weight, and the other values are relative
# to the number of layers in the model.
# By default, the same ranges are used across all components. For parameters
# that are sampled per component, the ranges are specified for each component.
[parameters]

# The different refusal direction scopes that can be applied to each trial.
direction_scope = [
    # Choose a refusal direction by interpolating between 2 layers and apply it globally.
    "global",
    # For each layer within range, apply the layer's own refusal direction to itself.
    "per layer",
]

# For the global direction scope, the layer from which to choose the refusal direction.
direction_fraction = { low = 0.4, high = 0.9 }

# The maximum weight with which to apply the abliteration. Set log = true to
# sample from the log space, which will select lower values more frequently.
# Note that low must be greater than 0 when log = true.
[parameters.max_weight]
"attn.o_proj"   = { low = 0.8, high = 1.5, log = false }
"mlp.down_proj" = { low = 0.8, high = 1.5, log = false }

# The position (layer) at which the maximum weight should be applied.
[parameters.max_weight_position_fraction]
"attn.o_proj"   = { low = 0.6, high = 1.0 }
"mlp.down_proj" = { low = 0.6, high = 1.0 }

# The minimum weight as a fraction of the maximum weight.
[parameters.min_weight_relative]
"attn.o_proj"   = { low = 0.0, high = 1.0 }
"mlp.down_proj" = { low = 0.0, high = 1.0 }

# The distance from max_weight_position across which the weight drops from
# max_weight to min_weight. Beyond this distance, the weight is set to 0.
[parameters.min_weight_distance_fraction]
"attn.o_proj"   = { low = 0.0, high = 0.6 }
"mlp.down_proj" = { low = 0.0, high = 0.6 }
